"""
Los informes que salen del gestor: la ficha de un cliente y el reporte del CRM.

Por que un `.docx` de verdad
----------------------------
La pantalla anterior los bajaba como un fichero `.doc` que por dentro era
HTML: una cadena concatenada, servida con el tipo `application/msword` y la
extension cambiada. Word lo abre --por compatibilidad con documentos de
Office 97-- pero avisa de que el formato no coincide con la extension, algunas
versiones se niegan, y Google Docs lo abre como una pagina web. Un informe que
el despacho manda a un cliente no puede empezar con un aviso de que el fichero
podria ser peligroso.

Aqui se construye un `.docx` real con `python-docx`, que el proyecto ya
instala --lo usa el formulario de insolvencia--, asi que no entra ninguna
dependencia nueva.

Se construye **por codigo y no desde una plantilla `.docx`**, al contrario que
insolvencia. Aquel documento es un formato legal con su maquetacion cerrada y
tiene sentido mantenerlo como fichero; estos dos son tablas de cifras que
cambian cuando cambie el panel, y una plantilla binaria es justo lo que nadie
puede revisar en un diff.

Que sale y que no
-----------------
Todo lo del panel interno, dinero incluido: estos informes son para el
despacho. La unica regla es la de siempre --el portal publico no ensena
cifras-- y aqui no aplica, porque a estas dos vistas solo llega quien tiene
sesion y grupo.
"""

import io
from datetime import date

from django.http import HttpResponse
from django.utils import timezone
from django.utils.translation import gettext as _
from docx import Document
from docx.shared import Pt

from .choices import Mandate
from .models import CaseFinanceModel, CaseModel, ClientModel

#: El membrete, en una sola linea. No es el logotipo: meter una imagen obliga
#: a resolver la ruta del estatico y a decidir que pasa si falta, y lo que el
#: documento necesita es decir de quien viene.
FIRMA = 'PROPENSIONES® ABOGADOS INTERNACIONAL'

#: Lo que se escribe donde no hay dato. El mismo que usa la pantalla.
VACIO = '—'


def _dinero(value: int | None) -> str:
    """
    Una cifra en pesos, con separador de miles y sin decimales.

    Se formatea aqui y no con `intcomma` de Django porque ese filtro es de
    plantilla y estos documentos no pasan por ninguna. El separador es el
    punto, que es el que usa Colombia y el que ya se ve en el panel.
    """
    return f'${value or 0:,.0f}'.replace(',', '.')


def _pie(document) -> None:
    """La linea de generacion, al final de todo informe."""
    momento = timezone.localtime().strftime('%d/%m/%Y %H:%M')
    parrafo = document.add_paragraph()
    corrida = parrafo.add_run(
        _('Generated by the Propensiones® case manager on %(when)s.')
        % {'when': momento}
    )
    corrida.italic = True
    corrida.font.size = Pt(8)


def _documento(titulo: str, subtitulo: str = ''):
    """Un documento vacio con el membrete y el titulo ya puestos."""
    document = Document()

    encabezado = document.add_paragraph()
    corrida = encabezado.add_run(FIRMA)
    corrida.bold = True
    corrida.font.size = Pt(9)

    document.add_heading(titulo, level=1)

    if subtitulo:
        document.add_paragraph(subtitulo)

    return document


def _pares(document, filas) -> None:
    """
    Un bloque de «etiqueta: valor», uno por linea.

    En parrafos y no en una tabla de dos columnas: una tabla obliga a Word a
    repartir anchos y, con un nombre largo al lado de una etiqueta corta, el
    resultado se ve peor que el texto corrido.
    """
    for etiqueta, valor in filas:
        parrafo = document.add_paragraph()
        parrafo.add_run(f'{etiqueta}: ').bold = True
        parrafo.add_run(str(valor if valor not in (None, '') else VACIO))


def _tabla(document, cabeceras, filas):
    """Una tabla con estilo de cuadricula y la cabecera en negrita."""
    tabla = document.add_table(rows=1, cols=len(cabeceras))
    tabla.style = 'Table Grid'

    for celda, texto in zip(tabla.rows[0].cells, cabeceras):
        celda.text = ''
        corrida = celda.paragraphs[0].add_run(str(texto))
        corrida.bold = True
        corrida.font.size = Pt(8)

    for fila in filas:
        celdas = tabla.add_row().cells
        for celda, texto in zip(celdas, fila):
            celda.text = ''
            celda.paragraphs[0].add_run(str(texto)).font.size = Pt(8)

    return tabla


def _descarga(document, nombre: str) -> HttpResponse:
    """
    El documento, ya como respuesta de descarga.

    Se escribe en memoria y no en un fichero temporal: son unas pocas decenas
    de kilobytes, y un temporal habria que borrarlo --y alguien tendria que
    acordarse de hacerlo cuando la respuesta falle a mitad--.
    """
    buffer = io.BytesIO()
    document.save(buffer)
    buffer.seek(0)

    respuesta = HttpResponse(
        buffer.read(),
        content_type=(
            'application/vnd.openxmlformats-officedocument'
            '.wordprocessingml.document'
        ),
    )
    respuesta['Content-Disposition'] = f'attachment; filename="{nombre}.docx"'
    return respuesta


# ---------------------------------------------------------------------------
# La ficha de un cliente
# ---------------------------------------------------------------------------

def _fila_de_asunto(case: CaseModel) -> list[str]:
    """Las diez columnas del cuadro aprobado, para un asunto."""
    finance = getattr(case, 'finance', None)

    if finance is None:
        return [
            case.get_service_display() or VACIO,
            case.area or VACIO,
            case.get_stage_display(),
            VACIO, VACIO, VACIO, VACIO, VACIO, VACIO,
        ]

    contingencia = (
        f'{finance.contingency_percentage} %'
        if finance.mandate == Mandate.CONTINGENCY
        else VACIO
    )

    return [
        case.get_service_display() or VACIO,
        case.area or VACIO,
        case.get_stage_display(),
        finance.elapsed,
        finance.get_mandate_display() or VACIO,
        str(finance.contingency_kind) or VACIO,
        contingencia,
        _dinero(finance.agreed or finance.expectation),
        _dinero(finance.paid),
        _dinero(finance.balance),
    ]


def client_report(client: ClientModel) -> HttpResponse:
    """La ficha interna de seguimiento de un cliente."""
    totals = CaseFinanceModel.objects.filter(case__client=client).totals()
    cases = (
        CaseModel.objects.filter(client=client)
        .select_related('finance')
        .order_by('-is_active', '-updated')
    )

    document = _documento(
        _('Internal case file'),
        _('Client file and financial summary.'),
    )

    _pares(document, [
        (_('Client'), client.full_name),
        (_('Identification'), client.identification),
        (_('Email'), client.email),
        (_('Phone'), client.phone),
        (_('Status'), _('ACTIVE') if client.is_active else _('INACTIVE')),
        (_('Cases'), cases.count()),
    ])

    document.add_heading(_('Financial summary'), level=2)
    _pares(document, [
        (_('Agreed'), _dinero(totals['agreed'])),
        (_('Collected'), _dinero(totals['paid'])),
        (_('Outstanding balance'), _dinero(totals['balance'])),
        (_('Contingency expectation'), _dinero(totals['expectation'])),
        (_('Potential pending'), _dinero(totals['potential_pending'])),
        (_('Projected total'), _dinero(totals['projected_total'])),
    ])

    document.add_heading(_('Cases'), level=2)
    _tabla(
        document,
        [
            _('Service'), _('Area'), _('Stage'), _('Elapsed'),
            _('Modality'), _('Contingency type'), _('Contingency'),
            _('Agreed / expectation'), _('Paid'), _('Owes'),
        ],
        [_fila_de_asunto(case) for case in cases],
    )

    _pie(document)

    nombre = _('File_%(identification)s_Propensiones') % {
        'identification': client.identification
    }
    return _descarga(document, nombre)


# ---------------------------------------------------------------------------
# El reporte del CRM
# ---------------------------------------------------------------------------

def crm_report() -> HttpResponse:
    """El consolidado del portafolio, con el detalle por asunto."""
    totals = CaseFinanceModel.objects.totals()
    areas = CaseFinanceModel.objects.by_area()

    filas = (
        CaseFinanceModel.objects.in_dashboard()
        .select_related('case', 'case__client')
        .order_by('case__client__full_name')
    )

    document = _documento(
        _('Management / CRM report'),
        _('Consolidated portfolio across all clients.'),
    )

    _pares(document, [
        (_('Agreed'), _dinero(totals['agreed'])),
        (_('Collected'), _dinero(totals['paid'])),
        (_('Outstanding balance'), _dinero(totals['balance'])),
        (_('Contingency expectation'), _dinero(totals['expectation'])),
        (_('Potential pending'), _dinero(totals['potential_pending'])),
        (_('Projected total'), _dinero(totals['projected_total'])),
        (_('Collection rate'), f"{totals['collection_rate']} %"),
    ])

    if areas:
        document.add_heading(_('Breakdown by area / case type'), level=2)
        _tabla(
            document,
            [_('Area / case type'), _('Total'), _('Share')],
            [
                [row['area'], _dinero(row['total']), f"{row['share']} %"]
                for row in areas
            ],
        )

    document.add_heading(_('Detail by case'), level=2)
    _tabla(
        document,
        [
            _('Client'), _('Identification'), _('Area'), _('Started'),
            _('Elapsed'), _('Modality'), _('Contingency type'),
            _('Agreed / expectation'), _('Paid'), _('Owes'),
        ],
        [
            [
                finance.case.client.full_name,
                finance.case.client.identification,
                finance.case.area or VACIO,
                finance.start_date.strftime('%m/%Y')
                if finance.start_date else VACIO,
                finance.elapsed,
                finance.get_mandate_display() or VACIO,
                str(finance.contingency_kind) or VACIO,
                _dinero(finance.agreed or finance.expectation),
                _dinero(finance.paid),
                _dinero(finance.balance),
            ]
            for finance in filas
        ],
    )

    _pie(document)

    nombre = _('CRM_report_%(date)s_Propensiones') % {
        'date': date.today().strftime('%Y-%m-%d')
    }
    return _descarga(document, nombre)
