# Generated by Django 4.2.13 on 2025-03-29 19:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_platform', '0005_alter_attlasinsolvencyauthmodel_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttlasInsolvencyFormModel',
            fields=[
                ('language', models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=4, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='priority')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('form_data', models.JSONField(blank=True, null=True, verbose_name='Form Data')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attlas_insolvency_forms', to='auth_platform.attlasinsolvencyauthmodel')),
            ],
            options={
                'verbose_name': 'Attlas Insolvency Form',
                'verbose_name_plural': 'Attlas Insolvency Forms',
                'db_table': 'apps_project_api_platform_attlas_insolvency_form',
                'ordering': ['-created'],
            },
        ),
    ]
