# Generated by Django 4.2.13 on 2025-04-18 00:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth_platform', '0007_alter_attlasinsolvencyauthconsultantsmodel_password'),
        ('insolvency_form', '0002_attlasinsolvencyformmodel_email_error_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttlasInsolvencyIncomeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=4, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='priority')),
                ('type', models.CharField(choices=[('SALARIO', 'Salario'), ('INDEPENDIENTE', 'Independiente'), ('PENSIONADO', 'Pensionado'), ('DESEMPLEADO', 'Desempleado'), ('OTRO', 'Otro')], max_length=20, verbose_name='Income Type')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Amount')),
            ],
            options={
                'verbose_name': 'Attlas Insolvency Income',
                'verbose_name_plural': 'Attlas Insolvency Incomes',
                'db_table': 'apps_project_api_platform_attlas_insolvency_income',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='AttlasInsolvencyResourceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=4, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='priority')),
                ('has_food_obligation', models.BooleanField(default=False, verbose_name='Has Food Obligation')),
                ('proposed_monthly_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Proposed Monthly Value')),
                ('children_count', models.IntegerField(default=0, verbose_name='Children Count')),
            ],
            options={
                'verbose_name': 'Attlas Insolvency Resource',
                'verbose_name_plural': 'Attlas Insolvency Resources',
                'db_table': 'apps_project_api_platform_attlas_insolvency_resource',
                'ordering': ['-created'],
            },
        ),
        migrations.RemoveField(
            model_name='attlasinsolvencyformmodel',
            name='form_data',
        ),
        migrations.AddField(
            model_name='attlasinsolvencyformmodel',
            name='accept_legal_requirements',
            field=models.BooleanField(default=False, verbose_name='Accepted Legal Requirements'),
        ),
        migrations.AddField(
            model_name='attlasinsolvencyformmodel',
            name='accept_terms_and_conditions',
            field=models.BooleanField(default=False, verbose_name='Accepted Terms and Conditions'),
        ),
        migrations.AddField(
            model_name='attlasinsolvencyformmodel',
            name='current_step',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Current Step'),
        ),
        migrations.AddField(
            model_name='attlasinsolvencyformmodel',
            name='debtor_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Debtor Location/Address'),
        ),
        migrations.AddField(
            model_name='attlasinsolvencyformmodel',
            name='debtor_birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Debtor Birth Date'),
        ),
        migrations.AddField(
            model_name='attlasinsolvencyformmodel',
            name='debtor_cell_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Debtor Cell Phone'),
        ),
        migrations.AddField(
            model_name='attlasinsolvencyformmodel',
            name='debtor_cessation_report',
            field=models.TextField(blank=True, null=True, verbose_name='Debtor Cessation Report'),
        ),
        migrations.AddField(
            model_name='attlasinsolvencyformmodel',
            name='debtor_document_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Debtor Document Number'),
        ),
        migrations.AddField(
            model_name='attlasinsolvencyformmodel',
            name='debtor_email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Debtor Email'),
        ),
        migrations.AddField(
            model_name='attlasinsolvencyformmodel',
            name='debtor_expedition_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Debtor Expedition City'),
        ),
        migrations.AddField(
            model_name='attlasinsolvencyformmodel',
            name='debtor_first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Debtor First Name'),
        ),
        migrations.AddField(
            model_name='attlasinsolvencyformmodel',
            name='debtor_is_merchant',
            field=models.BooleanField(default=False, verbose_name='Debtor is Merchant'),
        ),
        migrations.AddField(
            model_name='attlasinsolvencyformmodel',
            name='debtor_last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Debtor Last Name'),
        ),
        migrations.AddField(
            model_name='attlasinsolvencyformmodel',
            name='debtor_statement_accepted',
            field=models.BooleanField(default=False, verbose_name='Debtor Statement Accepted'),
        ),
        migrations.AddField(
            model_name='attlasinsolvencyformmodel',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Is Completed'),
        ),
        migrations.AddField(
            model_name='attlasinsolvencyformmodel',
            name='partner_cell_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Partner Phone'),
        ),
        migrations.AddField(
            model_name='attlasinsolvencyformmodel',
            name='partner_document_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Partner Document Number'),
        ),
        migrations.AddField(
            model_name='attlasinsolvencyformmodel',
            name='partner_email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Partner Email'),
        ),
        migrations.AddField(
            model_name='attlasinsolvencyformmodel',
            name='partner_last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Partner Last Name'),
        ),
        migrations.AddField(
            model_name='attlasinsolvencyformmodel',
            name='partner_marital_status',
            field=models.CharField(blank=True, choices=[('Soltero/a', 'Soltero/a'), ('Casado/a', 'Casado/a'), ('Divorciado/a', 'Divorciado/a'), ('Viudo/a', 'Viudo/a'), ('Unión Libre', 'Unión Libre'), ('Declaración Marital', 'Declaración Marital'), ('No aplica', 'No aplica')], max_length=100, null=True, verbose_name='Marital Status'),
        ),
        migrations.AddField(
            model_name='attlasinsolvencyformmodel',
            name='partner_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Partner Name'),
        ),
        migrations.AddField(
            model_name='attlasinsolvencyformmodel',
            name='partner_relationship_duration',
            field=models.IntegerField(blank=True, default=0, verbose_name='Partner Relationship Duration (months)'),
        ),
        migrations.AlterField(
            model_name='attlasinsolvencyformmodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='attlasinsolvencyformmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_platform.attlasinsolvencyauthmodel'),
        ),
        migrations.CreateModel(
            name='AttlasInsolvencySignatureModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=4, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='priority')),
                ('signature', models.TextField(blank=True, null=True, verbose_name='Signature')),
                ('form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signature_form', to='insolvency_form.attlasinsolvencyformmodel')),
            ],
            options={
                'verbose_name': 'Attlas Insolvency Signature',
                'verbose_name_plural': 'Attlas Insolvency Signatures',
                'db_table': 'apps_project_api_platform_attlas_insolvency_signature',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='AttlasInsolvencyResourceTableModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=4, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='priority')),
                ('title', models.CharField(max_length=100, verbose_name='Table Title')),
                ('relationship', models.CharField(choices=[('DEUDOR', 'DEUDOR'), ('ESPOSO', 'ESPOSO'), ('ESPOSA', 'ESPOSA'), ('PAREJA PERMANENTE', 'PAREJA PERMANENTE'), ('HIJO', 'HIJO'), ('HIJA', 'HIJA'), ('MADRE', 'MADRE'), ('PADRE', 'PADRE'), ('OTRO', 'OTRO')], max_length=20, verbose_name='Relationship')),
                ('disability', models.BooleanField(default=False, verbose_name='Has Disability')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Age')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True, verbose_name='Gender')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='insolvency_form.attlasinsolvencyresourcemodel', verbose_name='Resource')),
            ],
            options={
                'verbose_name': 'Attlas Insolvency Resource Table',
                'verbose_name_plural': 'Attlas Insolvency Resource Tables',
                'db_table': 'apps_project_api_platform_attlas_insolvency_resource_table',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='attlasinsolvencyresourcemodel',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='insolvency_form.attlasinsolvencyformmodel', verbose_name='Insolvency Form'),
        ),
        migrations.CreateModel(
            name='AttlasInsolvencyResourceItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=4, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='priority')),
                ('label', models.CharField(max_length=150, verbose_name='Expense Label')),
                ('legal_support', models.CharField(blank=True, max_length=255, verbose_name='Legal Support')),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Value')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='insolvency_form.attlasinsolvencyresourcetablemodel', verbose_name='Resource Table')),
            ],
            options={
                'verbose_name': 'Attlas Insolvency Resource Item',
                'verbose_name_plural': 'Attlas Insolvency Resource Items',
                'db_table': 'apps_project_api_platform_attlas_insolvency_resource_item',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='AttlasInsolvencyJudicialProcessModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=4, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='priority')),
                ('affectation', models.CharField(max_length=100, verbose_name='Affectation')),
                ('court', models.CharField(max_length=100, verbose_name='Court')),
                ('description', models.TextField(verbose_name='Description')),
                ('case_code', models.CharField(max_length=100, verbose_name='Case Code')),
                ('process_status', models.CharField(max_length=100, verbose_name='Process Status')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judicial_form', to='insolvency_form.attlasinsolvencyformmodel')),
            ],
            options={
                'verbose_name': 'Attlas Insolvency Judicial Process',
                'verbose_name_plural': 'Attlas Insolvency Judicial Processes',
                'db_table': 'apps_project_api_platform_attlas_insolvency_judicial_process',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='AttlasInsolvencyIncomeOtherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=4, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='priority')),
                ('detail', models.CharField(max_length=255, verbose_name='Detail')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount')),
                ('income', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomeother_income', to='insolvency_form.attlasinsolvencyincomemodel')),
            ],
            options={
                'verbose_name': 'Attlas Insolvency Income Other',
                'verbose_name_plural': 'Attlas Insolvency Incomes Other',
                'db_table': 'apps_project_api_platform_attlas_insolvency_income_other',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='attlasinsolvencyincomemodel',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='insolvency_form.attlasinsolvencyformmodel'),
        ),
        migrations.CreateModel(
            name='AttlasInsolvencyCreditorsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=4, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='priority')),
                ('creditor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Creditor')),
                ('nature_type', models.CharField(choices=[('CRÉDITO DE LIBRANZA', 'Crédito de Libranza'), ('CRÉDITO DE NOMINA', 'Crédito de Nómina'), ('CRÉDITO HIPOTECARIO', 'Crédito Hipotecario'), ('CRÉDITO DE GARANTÍA MOBILIARIA', 'Crédito de Garantía Mobiliaria'), ('CRÉDITO FISCAL O TRIBUTARIO', 'Crédito Fiscal o Tributario'), ('CRÉDITO DE LIBRE INVERSION', 'Crédito de Libre Inversión'), ('CRÉDITO PERSONAL', 'Crédito Personal'), ('CRÉDITO COMERCIAL', 'Crédito Comercial'), ('CRÉDITO ROTATIVO', 'Crédito Rotativo'), ('CRÉDITO EDUCATIVO O DE ESTUDIO', 'Crédito Educativo o de Estudio'), ('CRÉDITO DE CONSUMO', 'Crédito de Consumo'), ('OTRO', 'Otro')], max_length=100, verbose_name='Nature Type')),
                ('other_nature', models.CharField(blank=True, max_length=100, null=True, verbose_name='Other Nature')),
                ('personal_credit_interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Personal Credit Interest Rate')),
                ('personal_consanguinity', models.CharField(blank=True, choices=[('NN', 'No tengo parentesco'), ('1C', '1° consanguíneo: Compañero/a permanente, Padres e Hijos'), ('2C', '2° consanguíneo: Abuelos, Nietos y Hermanos'), ('3C', '3° consanguíneo: Tíos y Sobrinos'), ('4C', '4° consanguíneo: Primos y Sobrinos (nietos)'), ('1A', '1° afinidad: Suegros y Yerno/Nuera'), ('2A', '2° afinidad: Abuelos, Nietos y Hermanos del compañero/a permanente'), ('1CIV', '1° civil: Hijos adoptados y Padres Adoptivos')], max_length=100, null=True, verbose_name='Personal Consanguinity')),
                ('guarantee', models.CharField(blank=True, max_length=100, null=True, verbose_name='Guarantee')),
                ('capital_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Capital Value')),
                ('days_overdue', models.IntegerField(blank=True, null=True, verbose_name='Days Overdue')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditors_form', to='insolvency_form.attlasinsolvencyformmodel')),
            ],
            options={
                'verbose_name': 'Attlas Insolvency Creditors',
                'verbose_name_plural': 'Attlas Insolvency Creditors',
                'db_table': 'apps_project_api_platform_attlas_insolvency_creditors',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='AttlasInsolvencyAssetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=4, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='priority')),
                ('asset_type', models.CharField(choices=[('INMUEBLE', 'Inmueble'), ('MUEBLE', 'Mueble')], max_length=100, verbose_name='Asset Type')),
                ('name', models.CharField(max_length=100, verbose_name='Description/Name')),
                ('identification', models.CharField(max_length=100, verbose_name='Identification')),
                ('lien', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lien')),
                ('affectation', models.CharField(blank=True, max_length=100, null=True, verbose_name='Affectation')),
                ('legal_measure', models.JSONField(blank=True, null=True, verbose_name='Legal Measure')),
                ('patrimonial_society', models.CharField(blank=True, max_length=100, null=True, verbose_name='Patrimonial Society')),
                ('commercial_value', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Commercial Value')),
                ('exclusion', models.BooleanField(default=False, verbose_name='Exclusion')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_form', to='insolvency_form.attlasinsolvencyformmodel')),
            ],
            options={
                'verbose_name': 'Attlas Insolvency Asset',
                'verbose_name_plural': 'Attlas Insolvency Assets',
                'db_table': 'apps_project_api_platform_attlas_insolvency_asset',
                'ordering': ['-created'],
            },
        ),
    ]
