# Generated by Django 4.2.13 on 2025-04-22 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_platform', '0007_alter_attlasinsolvencyauthconsultantsmodel_password'),
        ('insolvency_form', '0004_attlasinsolvencycreditorsmodel_creditor_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attlasinsolvencyformmodel',
            name='debtor_sex',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='attlasinsolvencyformmodel',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insolvency_form', to='auth_platform.attlasinsolvencyauthmodel'),
        ),
        migrations.AddConstraint(
            model_name='attlasinsolvencyformmodel',
            constraint=models.UniqueConstraint(fields=('user',), name='one_form_per_user'),
        ),
    ]
