# Generated by Django 4.2.13 on 2025-04-22 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insolvency_form', '0005_attlasinsolvencyformmodel_debtor_sex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attlasinsolvencyjudicialprocessmodel',
            name='process_status',
            field=models.JSONField(max_length=100, verbose_name='Process Status'),
        ),
    ]
