# Generated by Django 4.2.13 on 2025-04-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insolvency_form', '0006_alter_attlasinsolvencyjudicialprocessmodel_process_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attlasinsolvencyresourcetablemodel',
            name='gender',
            field=models.CharField(blank=True, choices=[('MASCULINO', 'Male'), ('FEMENINO', 'Female')], max_length=10, null=True, verbose_name='Gender'),
        ),
    ]
