# Generated by Django 4.2.13 on 2025-04-25 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insolvency_form', '0007_alter_attlasinsolvencyresourcetablemodel_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='attlasinsolvencycreditorsmodel',
            name='credit_classification',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Credit Classification'),
        ),
    ]
