# Generated by Django 4.2.13 on 2025-04-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insolvency_form', '0008_attlasinsolvencycreditorsmodel_credit_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='attlasinsolvencysignaturemodel',
            name='client_ip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Client IP'),
        ),
        migrations.AddField(
            model_name='attlasinsolvencysignaturemodel',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='User Agent'),
        ),
    ]
