# Generated by Django 4.2.13 on 2025-05-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insolvency_form', '0009_attlasinsolvencysignaturemodel_client_ip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attlasinsolvencycreditorsmodel',
            name='credit_classification',
            field=models.CharField(blank=True, default='5', max_length=100, null=True, verbose_name='Credit Classification'),
        ),
        migrations.AlterField(
            model_name='attlasinsolvencyjudicialprocessmodel',
            name='court',
            field=models.TextField(verbose_name='Court'),
        ),
    ]
