# Generated by Django 4.2.21 on 2025-06-06 13:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('insolvency_form', '0010_alter_attlasinsolvencycreditorsmodel_credit_classification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attlasinsolvencyformmodel',
            name='partner_relationship_duration',
            field=models.IntegerField(blank=True, default=0, verbose_name='Partner Relationship Duration (years)'),
        ),
        migrations.CreateModel(
            name='AttlasInsolvencySummaryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=4, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='priority')),
                ('conciliation_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Conciliation Value')),
                ('propensiones_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Propensiones Value')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_form', to='insolvency_form.attlasinsolvencyformmodel')),
            ],
            options={
                'verbose_name': 'Attlas Insolvency Summary',
                'verbose_name_plural': 'Attlas Insolvency Summaries',
                'db_table': 'apps_project_api_platform_attlas_insolvency_summary',
                'ordering': ['-created'],
            },
        ),
    ]
