# Generated by Django 4.2.13 on 2025-03-17 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainfaqmodel',
            options={'ordering': ['default_order', '-created'], 'verbose_name': 'Main FAQ', 'verbose_name_plural': 'Main FAQs'},
        ),
        migrations.AlterModelOptions(
            name='otherfaqmodel',
            options={'ordering': ['default_order', '-created'], 'verbose_name': 'Other FAQ', 'verbose_name_plural': 'Other FAQs'},
        ),
    ]
