# Generated by Django 4.2.21 on 2026-05-22 15:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterestRateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=4, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='priority')),
                ('rate', models.DecimalField(decimal_places=2, help_text='Tasa efectiva anual (por ejemplo 45.27)', max_digits=6, verbose_name='Tasa de usura (%)')),
                ('effective_date', models.DateField(auto_now_add=True, help_text='Fecha desde la cual aplica esta tasa', verbose_name='Fecha de vigencia')),
            ],
            options={
                'verbose_name': 'Tasa de usura',
                'verbose_name_plural': 'Tasas de usura',
                'db_table': 'apps_platform_calculator_interest_rate',
                'ordering': ['-effective_date'],
            },
        ),
    ]
