# Generated by Django 4.2.21 on 2026-05-27 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InterestRateModel',
        ),
    ]
