# Generated by Django 4.2.7 on 2024-11-07 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IPBlockedModel',
        ),
    ]
