# Generated by Django 4.2.7 on 2024-11-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='state',
            field=models.CharField(blank=True, choices=[('UNATTENDED', 'Unattended'), ('ATTENDED', 'Attended'), ('IN_PROGRESS', 'In progress')], default='UNATTENDED', max_length=50, null=True, verbose_name='state'),
        ),
    ]
