# Generated by Django 4.2.7 on 2024-11-27 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_contactmodel_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modalbannermodel',
            name='image_file',
            field=models.ImageField(upload_to='modal_banners/', verbose_name='image file'),
        ),
    ]
