# Generated by Django 4.2.13 on 2025-02-25 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_modalbannermodel_image_file_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='from_page',
            field=models.CharField(blank=True, choices=[('PROPENSIONES', 'Propensiones'), ('ATTLAS', 'Attlas')], default='PROPENSIONES', max_length=255, null=True, verbose_name='from page'),
        ),
    ]
