# Generated by Django 4.2.21 on 2025-08-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contactmodel_from_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='from_page',
            field=models.CharField(blank=True, choices=[('PROPENSIONES', 'Propensiones'), ('ATTLAS', 'Attlas'), ('GEA', 'GEA')], default='PROPENSIONES', max_length=255, null=True, verbose_name='from page'),
        ),
    ]
