# Generated by Django 4.2.21 on 2026-01-27 22:16

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_contactmodel_from_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMemberModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=4, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='priority')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('full_name', models.CharField(max_length=255, verbose_name='full name')),
                ('role', models.CharField(max_length=255, verbose_name='role')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='slug')),
                ('linkedin_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='LinkedIn URL')),
                ('professional_summary', models.TextField(blank=True, null=True, verbose_name='professional summary')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='bio (extended)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/', verbose_name='photo')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='display order')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'db_table': 'apps_common_core_team_member',
                'ordering': ['display_order', 'full_name'],
            },
        ),
    ]
