# Generated by Django 4.2.13 on 2025-02-26 03:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialEducationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=4, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='priority')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='title en')),
                ('video_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='video url')),
                ('category', models.CharField(blank=True, max_length=255, null=True, verbose_name='category')),
                ('category_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='category en')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='description en')),
            ],
            options={
                'verbose_name': 'financial education',
                'verbose_name_plural': 'financial educations',
                'db_table': 'apps_project_api_financial_education',
                'ordering': ['-created'],
            },
        ),
    ]
