# Generated by Django 4.2.13 on 2025-02-26 03:50

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('financial_education', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialeducationmodel',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='financialeducationmodel',
            name='description_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='description en'),
        ),
        migrations.AlterField(
            model_name='financialeducationmodel',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='title'),
        ),
    ]
