# Generated by Django 4.2.13 on 2025-02-26 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_education', '0002_alter_financialeducationmodel_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialeducationmodel',
            options={'ordering': ['default_order', 'created'], 'verbose_name': 'financial education', 'verbose_name_plural': 'financial educations'},
        ),
    ]
