# Generated by Django 4.2.7 on 2024-11-07 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserLoginAttemptModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.IntegerField(default=0)),
                ('last_attempt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Login Attempt',
                'verbose_name_plural': 'User Login Attempts',
                'db_table': 'apps_project_common_account_userloginattempt',
            },
        ),
    ]
