# Generated by Django 5.2.17 on 2026-09-22 20:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case_manager", "0002_casemodel_paz_y_salvo_authorized"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseNoteModel",
            fields=[
                (
                    "language",
                    models.CharField(
                        blank=True,
                        choices=[("es", "Spanish"), ("en", "English")],
                        default="es",
                        max_length=4,
                        null=True,
                        verbose_name="language",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "default_order",
                    models.PositiveIntegerField(
                        blank=True, default=1, null=True, verbose_name="priority"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("INFO", "Update"),
                            ("BLOCKED", "On hold"),
                            ("DOCUMENT", "Document required"),
                            ("STAGE", "Stage change"),
                        ],
                        default="INFO",
                        max_length=20,
                        verbose_name="kind",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                (
                    "body",
                    models.TextField(
                        help_text="The client reads this as written. Keep it plain and say what, if anything, they have to do.",
                        verbose_name="body",
                    ),
                ),
                (
                    "visible_to_client",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck for notes that belong to the file, not to them.",
                        verbose_name="visible to the client",
                    ),
                ),
                (
                    "notified_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="When the client was emailed about this note, if ever.",
                        null=True,
                        verbose_name="notified at",
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="case_manager.casemodel",
                        verbose_name="case",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="case_notes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="written by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Case note",
                "verbose_name_plural": "Case notes",
                "db_table": "apps_project_case_manager_case_note",
                "ordering": ["-created"],
                "indexes": [
                    models.Index(
                        fields=["case", "-created"],
                        name="apps_projec_case_id_9ce33c_idx",
                    )
                ],
            },
        ),
    ]
