# Generated by Django 5.2.17 on 2026-09-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0004_clientmodel_code_blocked_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casemodel',
            name='area_other',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Otra área: ¿cuál?'),
        ),
        migrations.AddField(
            model_name='casemodel',
            name='procedure_other',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Otro trámite: ¿cuál?'),
        ),
        migrations.AddField(
            model_name='casemodel',
            name='second_subtype_other',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Otro segundo subnivel: ¿cuál?'),
        ),
        migrations.AddField(
            model_name='casemodel',
            name='service_other',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Otro servicio: ¿cuál?'),
        ),
        migrations.AddField(
            model_name='casemodel',
            name='subtype_other',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Otro subtipo: ¿cuál?'),
        ),
    ]
