# Generated by Django 4.2.21 on 2026-09-24 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0005_casemodel_area_other_casemodel_procedure_other_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casefinancemodel',
            name='payment_history',
            field=models.JSONField(blank=True, default=list, verbose_name='Historial de pagos'),
        ),
    ]
