# Generated by Django 4.2.21 on 2026-09-30 05:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0008_merge_20260924_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmodel',
            name='identification_type',
            field=models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('NIT', 'NIT'), ('CE', 'Cédula de extranjería'), ('PA', 'Pasaporte')], default='CC', max_length=3, verbose_name='document type'),
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='legal_rep_email',
            field=models.EmailField(blank=True, default='', max_length=255, verbose_name='legal representative email'),
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='legal_rep_identification',
            field=models.CharField(blank=True, default='', max_length=20, validators=[django.core.validators.RegexValidator('^[0-9A-Za-z]+$', 'The identification must contain letters and digits only.')], verbose_name='legal representative identification'),
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='legal_rep_identification_type',
            field=models.CharField(blank=True, choices=[('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extranjería'), ('PA', 'Pasaporte')], default='', max_length=3, verbose_name='legal representative document type'),
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='legal_rep_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='legal representative'),
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='legal_rep_phone',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='legal representative phone'),
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='verification_digit',
            field=models.CharField(blank=True, default='', help_text='Only for NIT: the digit after the hyphen.', max_length=1, verbose_name='check digit'),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='identification',
            field=models.CharField(help_text='The number only, no dots, spaces or check digit. Passports may include letters.', max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[0-9A-Za-z]+$', 'The identification must contain letters and digits only.')], verbose_name='identification'),
        ),
    ]
