# Generated by Django 4.2.21 on 2026-09-30 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0009_client_document_type_nit_legal_rep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casefinancemodel',
            name='mandate',
            field=models.CharField(choices=[('Ad honorem', 'Ad honorem'), ('Cuota litis', 'Cuota litis'), ('Curaduría', 'Curaduría'), ('Modalidad de pago', 'Fixed fees (installments)')], max_length=30, verbose_name='fee arrangement'),
        ),
    ]
