# Generated by Django 4.2.13 on 2025-03-24 02:13

from django.db import migrations, models
import django.utils.timezone
import encrypted_model_fields.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttlasInsolvencyAuth',
            fields=[
                ('language', models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=4, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='priority')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('document_number', encrypted_model_fields.fields.EncryptedCharField()),
                ('document_issue_date', encrypted_model_fields.fields.EncryptedDateField()),
                ('birth_date', encrypted_model_fields.fields.EncryptedDateField()),
            ],
            options={
                'verbose_name': 'Attlas Insolvency Auth',
                'verbose_name_plural': 'Attlas Insolvency Auths',
                'db_table': 'apps_project_api_platform_attlas_insolvency_auth',
                'ordering': ['-created'],
            },
        ),
    ]
