# Generated by Django 4.2.13 on 2025-03-24 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_platform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attlasinsolvencyauth',
            name='birth_date_hash',
            field=models.CharField(db_index=True, default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attlasinsolvencyauth',
            name='document_issue_date_hash',
            field=models.CharField(db_index=True, default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attlasinsolvencyauth',
            name='document_number_hash',
            field=models.CharField(db_index=True, default='', max_length=64),
            preserve_default=False,
        ),
    ]
