# Generated by Django 4.2.13 on 2025-03-24 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_platform', '0002_attlasinsolvencyauth_birth_date_hash_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AttlasInsolvencyAuth',
            new_name='AttlasInsolvencyAuthModel',
        ),
    ]
