# Generated by Django 4.2.13 on 2025-03-28 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_platform', '0003_rename_attlasinsolvencyauth_attlasinsolvencyauthmodel'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attlasinsolvencyauthmodel',
            unique_together={('document_number', 'document_issue_date', 'birth_date')},
        ),
    ]
