# Generated by Django 4.2.13 on 2025-03-28 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_platform', '0004_alter_attlasinsolvencyauthmodel_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attlasinsolvencyauthmodel',
            unique_together={('document_number_hash', 'document_issue_date_hash', 'birth_date_hash')},
        ),
    ]
