# Generated by Django 4.2.13 on 2025-04-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_platform', '0006_attlasinsolvencyauthconsultantsmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attlasinsolvencyauthconsultantsmodel',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='password'),
        ),
    ]
