# Generated by Django 4.2.7 on 2024-11-07 06:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPBlockedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=4, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='priority')),
                ('is_active', models.BooleanField(default=True, verbose_name='is blocked')),
                ('current_ip', models.CharField(max_length=150, verbose_name='current user IP')),
                ('reason', models.CharField(choices=[('RA', 'Attempts to obtain forbidden urls'), ('SK', 'Multiple failed security key entry attempts')], default='RA', max_length=4, verbose_name='reason')),
                ('blocked_until', models.DateTimeField(blank=True, null=True, verbose_name='blocked until')),
                ('session_info', models.JSONField(blank=True, default=dict, verbose_name='session information')),
            ],
            options={
                'verbose_name': 'Blocked IP',
                'verbose_name_plural': 'Blocked IPs',
                'db_table': 'apps_common_utils_iptoblock',
            },
        ),
    ]
