# Generated by Django 4.2.13 on 2025-02-26 17:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhiteListedIPModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=4, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='priority')),
                ('current_ip', models.CharField(max_length=150, verbose_name='current user IP')),
                ('reason', models.CharField(blank=True, max_length=150, null=True, verbose_name='reason')),
            ],
            options={
                'verbose_name': 'WhiteListed IP',
                'verbose_name_plural': 'WhiteListed IPs',
                'db_table': 'apps_utils_whitelistedip',
            },
        ),
    ]
