# Generated by Django 5.2.17 on 2026-09-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0002_whitelistedipmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ipblockedmodel",
            name="reason",
            field=models.CharField(
                choices=[
                    ("RA", "Attempts to obtain forbidden urls"),
                    ("SK", "Multiple failed security key entry attempts"),
                    (
                        "CQ",
                        "Multiple failed access key attempts on the case query portal",
                    ),
                ],
                default="RA",
                max_length=4,
                verbose_name="reason",
            ),
        ),
    ]
