# Generated by Django 4.2.21 on 2026-09-30 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_alter_ipblockedmodel_reason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipblockedmodel',
            options={'ordering': ['-created', '-updated'], 'verbose_name': 'Blocked IP', 'verbose_name_plural': 'Blocked IPs'},
        ),
        migrations.AddField(
            model_name='ipblockedmodel',
            name='attempt_count',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='attempts'),
        ),
        migrations.AddField(
            model_name='ipblockedmodel',
            name='country',
            field=models.CharField(blank=True, db_index=True, default='', max_length=2, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='ipblockedmodel',
            name='first_seen',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='first detection'),
        ),
        migrations.AddField(
            model_name='ipblockedmodel',
            name='is_datacenter',
            field=models.BooleanField(db_index=True, default=False, help_text='The IP belongs to a hosting provider range. A person browses from a home or office address; a server does not browse.', verbose_name='datacenter or cloud'),
        ),
        migrations.AddField(
            model_name='ipblockedmodel',
            name='last_seen',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='last detection'),
        ),
        migrations.AddField(
            model_name='ipblockedmodel',
            name='matched_pattern',
            field=models.CharField(blank=True, default='', help_text='What tripped the block: the trap term, or the signature.', max_length=150, verbose_name='pattern'),
        ),
        migrations.AddField(
            model_name='ipblockedmodel',
            name='network_owner',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='network / ASN'),
        ),
        migrations.AddField(
            model_name='ipblockedmodel',
            name='unique_paths',
            field=models.PositiveIntegerField(default=0, help_text='Distinct paths tried. Many attempts on one path is someone retrying; a few attempts on many paths is a scan.', verbose_name='unique paths'),
        ),
        migrations.AddField(
            model_name='ipblockedmodel',
            name='user_agent',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='user agent'),
        ),
        migrations.AlterField(
            model_name='ipblockedmodel',
            name='reason',
            field=models.CharField(choices=[('RA', 'Attempts to obtain forbidden urls'), ('SK', 'Multiple failed security key entry attempts'), ('PE', 'Enumerating paths that do not exist'), ('SC', 'Known scanning tool'), ('CQ', 'Multiple failed access key attempts on the case query portal')], default='RA', max_length=4, verbose_name='reason'),
        ),
        migrations.AddIndex(
            model_name='ipblockedmodel',
            index=models.Index(fields=['current_ip', 'is_active', 'blocked_until'], name='ipblocked_lookup_idx'),
        ),
    ]
