# Generated by Django 5.2.17 on 2026-09-22 14:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CaseModel",
            fields=[
                (
                    "language",
                    models.CharField(
                        blank=True,
                        choices=[("es", "Spanish"), ("en", "English")],
                        default="es",
                        max_length=4,
                        null=True,
                        verbose_name="language",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
                (
                    "default_order",
                    models.PositiveIntegerField(
                        blank=True, default=1, null=True, verbose_name="priority"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("Administrativo", "Administrativo"),
                            ("Representación judicial", "Representación judicial"),
                            ("Conciliación", "Conciliación"),
                            ("Consultoría", "Consultoría"),
                            ("Investigación de campo", "Investigación de campo"),
                            ("Otro", "Otro"),
                        ],
                        max_length=50,
                        verbose_name="contracted service",
                    ),
                ),
                (
                    "procedure",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Administrativo", "Administrativo"),
                            ("Privado", "Privado"),
                            ("Acción de tutela", "Acción de tutela"),
                            ("Proceso ordinario", "Proceso ordinario"),
                            ("Proceso ejecutivo", "Proceso ejecutivo"),
                            ("Conciliación", "Conciliación"),
                            ("Investigación de campo", "Investigación de campo"),
                            ("Trámite notarial", "Trámite notarial"),
                            ("Trámite registral", "Trámite registral"),
                            ("Querella policiva", "Querella policiva"),
                            ("Otro", "Otro"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="procedure type",
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "Pensional / Seguridad Social",
                                "Pensional / Seguridad Social",
                            ),
                            ("Laboral", "Laboral"),
                            ("Civil", "Civil"),
                            ("Familia", "Familia"),
                            ("Sucesiones", "Sucesiones"),
                            ("Administrativo", "Administrativo"),
                            ("Seguros", "Seguros"),
                            ("Insolvencia", "Insolvencia"),
                            ("Conciliación", "Conciliación"),
                            ("Penal", "Penal"),
                            ("Consumidor", "Consumidor"),
                            ("Comercial / Empresarial", "Comercial / Empresarial"),
                            ("Investigación de campo", "Investigación de campo"),
                            ("Otro", "Otro"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="area / case type",
                    ),
                ),
                (
                    "subtype",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="subtype / speciality",
                    ),
                ),
                (
                    "second_subtype",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="second sublevel",
                    ),
                ),
                (
                    "stage",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Documentos recibidos"),
                            (1, "En estudio"),
                            (2, "En trámite"),
                            (3, "En desarrollo"),
                            (4, "Etapa final"),
                            (5, "Finalizado"),
                        ],
                        default=0,
                        verbose_name="stage",
                    ),
                ),
                (
                    "instance",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="current stage / instance",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="case in force"),
                ),
                (
                    "case_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="case number",
                    ),
                ),
                (
                    "court",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Juzgado Municipal", "Juzgado Municipal"),
                            ("Juzgado del Circuito", "Juzgado del Circuito"),
                            ("Tribunal Superior", "Tribunal Superior"),
                            ("Corte Suprema de Justicia", "Corte Suprema de Justicia"),
                            ("Consejo de Estado", "Consejo de Estado"),
                            ("Corte Constitucional", "Corte Constitucional"),
                            ("Superintendencia", "Superintendencia"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="court / judicial authority",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="city of the process",
                    ),
                ),
                (
                    "sector",
                    models.CharField(
                        blank=True,
                        choices=[("Público", "Público"), ("Privado", "Privado")],
                        max_length=20,
                        null=True,
                        verbose_name="nature of the procedure",
                    ),
                ),
                (
                    "entity",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="entity / company",
                    ),
                ),
                (
                    "administrative_case_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="reference number",
                    ),
                ),
                (
                    "administrative_city",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="city of the procedure",
                    ),
                ),
                (
                    "police_instance",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Primera instancia", "Primera instancia"),
                            ("Segunda instancia", "Segunda instancia"),
                        ],
                        max_length=30,
                        null=True,
                        verbose_name="police instance",
                    ),
                ),
                (
                    "police_office",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="police inspection / authority",
                    ),
                ),
                (
                    "police_case_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="police case number",
                    ),
                ),
                (
                    "police_city",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="city / municipality",
                    ),
                ),
            ],
            options={
                "verbose_name": "Case",
                "verbose_name_plural": "Cases",
                "db_table": "apps_project_case_manager_case",
                "ordering": ["-updated"],
            },
        ),
        migrations.CreateModel(
            name="CaseFinanceModel",
            fields=[
                (
                    "language",
                    models.CharField(
                        blank=True,
                        choices=[("es", "Spanish"), ("en", "English")],
                        default="es",
                        max_length=4,
                        null=True,
                        verbose_name="language",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "default_order",
                    models.PositiveIntegerField(
                        blank=True, default=1, null=True, verbose_name="priority"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True,
                        help_text="Month and year the matter started.",
                        null=True,
                        verbose_name="start date",
                    ),
                ),
                (
                    "mandate",
                    models.CharField(
                        choices=[
                            ("Cuota litis", "Cuota litis"),
                            ("Modalidad de pago", "Modalidad de pago"),
                            ("Ad honorem", "Ad honorem"),
                            ("Curaduría", "Curaduría"),
                        ],
                        max_length=30,
                        verbose_name="contract modality",
                    ),
                ),
                (
                    "contingency_percentage",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="0 means a closed fixed value, not a contingency.",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="contingency percentage",
                    ),
                ),
                (
                    "contingency_value",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="contingency value"
                    ),
                ),
                (
                    "agreed_fee",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="agreed fee"
                    ),
                ),
                (
                    "paid_amount",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="paid amount"
                    ),
                ),
                (
                    "show_in_dashboard",
                    models.BooleanField(
                        default=True, verbose_name="include in the financial dashboard"
                    ),
                ),
                (
                    "case",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="finance",
                        to="case_manager.casemodel",
                        verbose_name="case",
                    ),
                ),
            ],
            options={
                "verbose_name": "Case finance",
                "verbose_name_plural": "Case finances",
                "db_table": "apps_project_case_manager_case_finance",
                "ordering": ["-updated"],
            },
        ),
        migrations.CreateModel(
            name="ClientModel",
            fields=[
                (
                    "language",
                    models.CharField(
                        blank=True,
                        choices=[("es", "Spanish"), ("en", "English")],
                        default="es",
                        max_length=4,
                        null=True,
                        verbose_name="language",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
                (
                    "default_order",
                    models.PositiveIntegerField(
                        blank=True, default=1, null=True, verbose_name="priority"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identification",
                    models.CharField(
                        help_text="Digits only, no dots or spaces.",
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d+$", "The identification must contain digits only."
                            )
                        ],
                        verbose_name="identification",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=255, verbose_name="full name"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=255, null=True, verbose_name="email"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="phone"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="An inactive client identifies correctly but cannot see the case.",
                        verbose_name="service in force",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
                "db_table": "apps_project_case_manager_client",
                "ordering": ["full_name"],
                "indexes": [
                    models.Index(
                        fields=["identification"], name="apps_projec_identif_5766d5_idx"
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="casemodel",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cases",
                to="case_manager.clientmodel",
                verbose_name="client",
            ),
        ),
        migrations.AddIndex(
            model_name="casemodel",
            index=models.Index(
                fields=["client", "-updated"], name="apps_projec_client__4a67d6_idx"
            ),
        ),
    ]
