# Generated by Django 5.2.17 on 2026-09-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case_manager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="casemodel",
            name="paz_y_salvo_authorized",
            field=models.BooleanField(
                default=False,
                help_text="The client can print the settlement letter only when the firm authorizes it here.",
                verbose_name="paz y salvo authorized",
            ),
        ),
    ]
