# Generated by Django 5.2.17 on 2026-09-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case_manager", "0003_casenotemodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientmodel",
            name="code_blocked_until",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="codes blocked until",
            ),
        ),
        migrations.AddField(
            model_name="clientmodel",
            name="code_sends",
            field=models.PositiveSmallIntegerField(
                default=0,
                editable=False,
                verbose_name="codes sent in the current cycle",
            ),
        ),
        migrations.AddField(
            model_name="clientmodel",
            name="last_code_sent_at",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="last code sent at"
            ),
        ),
    ]
