# Generated by Django 5.2.17 on 2026-09-24 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0005_casemodel_area_other_casemodel_procedure_other_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casefinancemodel',
            name='mandate',
            field=models.CharField(choices=[('Ad honorem', 'Ad honorem'), ('Cuota litis', 'Cuota litis'), ('Curaduría', 'Curaduría'), ('Modalidad de pago', 'Modalidad de pago')], max_length=30, verbose_name='contract modality'),
        ),
        migrations.AlterField(
            model_name='casemodel',
            name='area',
            field=models.CharField(blank=True, choices=[('Administrativo', 'Administrativo'), ('Civil', 'Civil'), ('Comercial / Empresarial', 'Comercial / Empresarial'), ('Conciliación', 'Conciliación'), ('Consumidor', 'Consumidor'), ('Familia', 'Familia'), ('Insolvencia', 'Insolvencia'), ('Investigación de campo', 'Investigación de campo'), ('Laboral', 'Laboral'), ('Penal', 'Penal'), ('Pensional / Seguridad Social', 'Pensional / Seguridad Social'), ('Seguros', 'Seguros'), ('Sucesiones', 'Sucesiones'), ('Otro', 'Otro')], max_length=50, null=True, verbose_name='area / case type'),
        ),
        migrations.AlterField(
            model_name='casemodel',
            name='court',
            field=models.CharField(blank=True, choices=[('Consejo de Estado', 'Consejo de Estado'), ('Corte Constitucional', 'Corte Constitucional'), ('Corte Suprema de Justicia', 'Corte Suprema de Justicia'), ('Juzgado Administrativo', 'Juzgado Administrativo'), ('Juzgado del Circuito', 'Juzgado del Circuito'), ('Juzgado Municipal', 'Juzgado Municipal'), ('Superintendencia', 'Superintendencia'), ('Tribunal Administrativo', 'Tribunal Administrativo'), ('Tribunal Superior', 'Tribunal Superior')], max_length=100, null=True, verbose_name='court / judicial authority'),
        ),
        migrations.AlterField(
            model_name='casemodel',
            name='procedure',
            field=models.CharField(blank=True, choices=[('Acción de tutela', 'Acción de tutela'), ('Administrativo', 'Administrativo'), ('Conciliación', 'Conciliación'), ('Investigación de campo', 'Investigación de campo'), ('Privado', 'Privado'), ('Proceso ejecutivo', 'Proceso ejecutivo'), ('Proceso ordinario', 'Proceso ordinario'), ('Querella policiva', 'Querella policiva'), ('Trámite notarial', 'Trámite notarial'), ('Trámite registral', 'Trámite registral'), ('Otro', 'Otro')], max_length=50, null=True, verbose_name='procedure type'),
        ),
        migrations.AlterField(
            model_name='casemodel',
            name='sector',
            field=models.CharField(blank=True, choices=[('Privado', 'Privado'), ('Público', 'Público')], max_length=20, null=True, verbose_name='nature of the procedure'),
        ),
        migrations.AlterField(
            model_name='casemodel',
            name='service',
            field=models.CharField(choices=[('Administrativo', 'Administrativo'), ('Conciliación', 'Conciliación'), ('Consultoría', 'Consultoría'), ('Investigación de campo', 'Investigación de campo'), ('Representación judicial', 'Representación judicial'), ('Otro', 'Otro')], max_length=50, verbose_name='contracted service'),
        ),
    ]
