# Generated by Django 5.2.17 on 2026-09-24 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0006_alter_casefinancemodel_mandate_alter_casemodel_area_and_more'),
        ('case_manager', '0006_payment_history'),
    ]

    operations = [
    ]
