# Generated by Django 5.2.17 on 2026-09-24 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0007_merge_20260923_2240'),
        ('case_manager', '0007_sync_classification_choices'),
    ]

    operations = [
    ]
