# Generated by Django 4.2.21 on 2026-09-30 05:35

import apps.project.api.platform.case_manager.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0010_fee_arrangement_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='casemodel',
            name='paz_y_salvo_authorized_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='Set when the settlement letter is authorized and cleared when it is withdrawn. It is the date printed on the document.', null=True, verbose_name='paz y salvo authorized at'),
        ),
        migrations.CreateModel(
            name='PazYSalvoDocumentModel',
            fields=[
                ('language', models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=4, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='priority')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('authorized_at', models.DateTimeField(verbose_name='authorized at')),
                ('reference_snapshot', models.CharField(blank=True, max_length=255, verbose_name='reference')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CERTIFIED', 'Certified'), ('FAILED', 'Failed'), ('REVOKED', 'Revoked')], db_index=True, default='PENDING', max_length=12, verbose_name='status')),
                ('active_slot', models.PositiveSmallIntegerField(blank=True, editable=False, null=True)),
                ('idempotency_key', models.CharField(editable=False, max_length=64, unique=True, verbose_name='idempotency key')),
                ('source_file', models.FileField(blank=True, max_length=255, storage=apps.project.api.platform.case_manager.models.PrivateMediaStorage(), upload_to=apps.project.api.platform.case_manager.models.paz_y_salvo_source_path, verbose_name='source file')),
                ('public_copy_file', models.FileField(blank=True, max_length=255, storage=apps.project.api.platform.case_manager.models.PrivateMediaStorage(), upload_to=apps.project.api.platform.case_manager.models.paz_y_salvo_public_path, verbose_name='distributable copy')),
                ('gea_document_id', models.CharField(blank=True, max_length=64, verbose_name='gea document id')),
                ('gea_code', models.CharField(blank=True, max_length=64, verbose_name='gea code')),
                ('verification_url', models.URLField(blank=True, max_length=500, verbose_name='verification URL')),
                ('source_hash', models.CharField(blank=True, max_length=128)),
                ('public_copy_hash', models.CharField(blank=True, max_length=128)),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='attempts')),
                ('last_error', models.TextField(blank=True, verbose_name='last error')),
                ('certified_at', models.DateTimeField(blank=True, null=True, verbose_name='certified at')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='revoked at')),
                ('gea_revoked', models.BooleanField(default=False, verbose_name='revocation sent to gea')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paz_y_salvo_documents', to='case_manager.casemodel', verbose_name='case')),
            ],
            options={
                'verbose_name': 'Settlement letter document',
                'verbose_name_plural': 'Settlement letter documents',
                'db_table': 'apps_project_case_manager_paz_y_salvo',
                'ordering': ['-authorized_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='pazysalvodocumentmodel',
            constraint=models.UniqueConstraint(fields=('case', 'active_slot'), name='case_manager_one_active_paz_y_salvo'),
        ),
    ]
