# Generated by Django 4.2.13 on 2025-02-26 03:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PQRSModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=4, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='priority')),
                ('request_type', models.CharField(blank=True, choices=[('ACCESS', 'Access'), ('UPDATE', 'Update'), ('RECTIFICATION', 'Rectification'), ('DELETE', 'Delete'), ('REQUEST', 'Request'), ('CLAIM', 'Claim'), ('COMPLAINT', 'Complaint'), ('INQUIRY', 'Inquiry'), ('OTHER', 'Other')], default='OTHER', max_length=255, null=True, verbose_name='request type')),
                ('is_legal_entity', models.BooleanField(default=False, verbose_name='is legal entity')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='company name')),
                ('nit', models.CharField(blank=True, max_length=255, null=True, verbose_name='NIT')),
                ('legal_representative', models.CharField(blank=True, max_length=255, null=True, verbose_name='legal representative')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('surname', models.CharField(max_length=255, verbose_name='surname')),
                ('id_type', models.CharField(blank=True, choices=[('CC', 'CC'), ('CE', 'CE'), ('PA', 'PA'), ('OTHER', 'Other')], default='CC', max_length=255, null=True, verbose_name='ID type')),
                ('id_number', models.CharField(max_length=255, verbose_name='ID number')),
                ('country', models.CharField(max_length=255, verbose_name='country')),
                ('city', models.CharField(max_length=255, verbose_name='city')),
                ('addres', models.CharField(max_length=255, verbose_name='addres')),
                ('email', models.EmailField(max_length=255, verbose_name='email')),
                ('cell_prefix', models.CharField(max_length=10, verbose_name='cell prefix')),
                ('cellphone', models.CharField(max_length=15, verbose_name='cellphone')),
                ('documents', models.URLField(blank=True, null=True, verbose_name='documents')),
                ('description', models.TextField(verbose_name='description')),
                ('contact_methods', models.CharField(blank=True, max_length=255, null=True, verbose_name='contact methods')),
                ('contact_email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='contact email')),
                ('contact_cell_prefix', models.CharField(blank=True, max_length=10, null=True, verbose_name='contact cell prefix')),
                ('contact_cellphone', models.CharField(blank=True, max_length=15, null=True, verbose_name='contact cellphone')),
                ('contact_phone_prefix', models.CharField(blank=True, max_length=10, null=True, verbose_name='contact phone prefix')),
                ('contact_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='contact phone')),
                ('terms_accepted', models.BooleanField(default=False, verbose_name='terms accepted')),
            ],
            options={
                'verbose_name': 'PQRS',
                'verbose_name_plural': 'PQRS',
                'db_table': 'apps_project_api_pqrs',
                'ordering': ['-created'],
            },
        ),
    ]
