# Generated by Django 4.2.13 on 2025-02-26 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pqrsmodel',
            old_name='request_type',
            new_name='request_type_en',
        ),
        migrations.AddField(
            model_name='pqrsmodel',
            name='request_type_es',
            field=models.CharField(blank=True, choices=[('ACCESS', 'Access'), ('UPDATE', 'Update'), ('RECTIFICATION', 'Rectification'), ('DELETE', 'Delete'), ('REQUEST', 'Request'), ('CLAIM', 'Claim'), ('COMPLAINT', 'Complaint'), ('INQUIRY', 'Inquiry'), ('OTHER', 'Other')], default='OTHER', max_length=255, null=True, verbose_name='request type'),
        ),
    ]
