# Generated by Django 4.2.21 on 2026-05-30 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0002_rename_request_type_pqrsmodel_request_type_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pqrsmodel',
            old_name='addres',
            new_name='address',
        ),
    ]