# Generated by Django 5.2.17 on 2026-09-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pqrs", "0003_rename_pqrsmodel_addres_pqrsmodel_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pqrsmodel",
            name="address",
            field=models.CharField(default="", max_length=255, verbose_name="address"),
        ),
    ]
